# These are supported funding model platforms

github: wallyjaytechy
patreon: 
open_collective: 
ko_fi:
tidelift: 
community_bridge: 
liberapay:
issuehunt: 
lfx_crowdfunding: 
polar:
buy_me_a_coffee: wallyjaytechy
custom: https://github.com/wallyjaytechy/wallyjaytechy
