# These are supported funding model platforms

github: [wallyjaytechy]
patreon: 
open_collective: wallyjaytechy
ko_fi:
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay:
issuehunt: 
lfx_crowdfunding: cloud-foundry
polar:
buy_me_a_coffee: wallyjaytech
custom: 
